version: "2"
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecksumtype
    - goconst
    - gocritic
    - gocyclo
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - grouper
    - importas
    - inamedparam
    - interfacebloat
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - musttag
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - testableexamples
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
    - zerologlint
  settings:
    errcheck:
      check-type-assertions: true
    errorlint:
      errorf: false
    gocritic:
      disabled-checks:
        - whyNoLint
        - commentedOutCode
      enabled-tags:
        - diagnostic
        - style
        - performance
    govet:
      enable:
        - asmdecl
        - assign
        - atomic
        - atomicalign
        - bools
        - buildtag
        - cgocall
        - composites
        - copylocks
        - deepequalerrors
        - errorsas
        - fieldalignment
        - findcall
        - framepointer
        - httpresponse
        - ifaceassert
        - loopclosure
        - lostcancel
        - nilfunc
        - nilness
        - printf
        - reflectvaluecompare
        - shift
        - sigchanyzer
        - sortslice
        - stdmethods
        - stringintconv
        - structtag
        - testinggoroutine
        - tests
        - unmarshal
        - unreachable
        - unsafeptr
        - unusedresult
        - unusedwrite
    nolintlint:
      require-specific: true
    revive:
      rules:
        - name: add-constant
          arguments:
            - allowFloats: "0.0"
              allowInts: 0,1,2,3,4,5,6,10,64,1024
              allowStrs: '"","}","{",":"'
              maxLitCount: "3"
          disabled: false
        - name: atomic
          disabled: false
        - name: bool-literal-in-expr
          disabled: false
        - name: call-to-gc
          disabled: false
        - name: confusing-naming
          disabled: false
        - name: confusing-results
          disabled: false
        - name: constant-logical-expr
          disabled: false
        - name: deep-exit
          disabled: false
        - name: defer
          disabled: false
        - name: duplicated-imports
          disabled: false
        - name: early-return
          disabled: false
        - name: empty-block
          disabled: false
        - name: empty-lines
          disabled: false
        - name: empty-lines
          disabled: false
        - name: error-naming
          disabled: false
        - name: error-return
          disabled: false
        - name: error-strings
          disabled: false
        - name: errorf
          disabled: false
        - name: get-return
          disabled: false
        - name: identical-branches
          disabled: false
        - name: if-return
          disabled: false
        - name: increment-decrement
          disabled: false
        - name: indent-error-flow
          disabled: false
        - name: import-shadowing
          disabled: false
        - name: modifies-parameter
          disabled: false
        - name: modifies-value-receiver
          disabled: false
        - name: optimize-operands-order
          disabled: false
        - name: range
          disabled: false
        - name: range-val-in-closure
          disabled: false
        - name: range-val-address
          disabled: false
        - name: receiver-naming
          disabled: false
        - name: redefines-builtin-id
          disabled: false
        - name: string-of-int
          disabled: false
        - name: struct-tag
          disabled: false
        - name: superfluous-else
          disabled: false
        - name: time-equal
          disabled: false
        - name: time-naming
          disabled: false
        - name: var-naming
          disabled: false
        - name: var-declaration
          disabled: false
        - name: unconditional-recursion
          disabled: false
        - name: unexported-naming
          disabled: false
        - name: unhandled-error
          disabled: false
        - name: unnecessary-stmt
          disabled: false
        - name: unreachable-code
          disabled: false
        - name: unused-parameter
          disabled: false
        - name: unused-receiver
          disabled: false
        - name: useless-break
          disabled: false
        - name: waitgroup-by-value
          disabled: false
    staticcheck:
      checks:
        - all
        # - -ST1005
        - -ST1003  # Allow underscores in package names
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gocyclo
          - govet
        path: (.+)_test\.go
      - path: (.+)\.go$
        text: 'add-constant: string literal "(ReadBool|ReadUint|ReadString|ReadNBytes)'
      - path: (.+)\.go$
        text: 'unhandled-error: Unhandled error in call to function b.(WriteString|Write)'
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: false
  new: false
  fix: false
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
